Invalid HTTP_HOST header: '192.168.11.37:8000'. You may need to add '192.168.11.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/usr/local/lib/python3.8/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/usr/local/lib/python3.8/site-packages/django/http/request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '192.168.11.37:8000'. You may need to add '192.168.11.37' to ALLOWED_HOSTS.
Internal Server Error: /admin/TaskManagerApp/person/add/
Traceback (most recent call last):
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/contrib/admin/options.py", line 622, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/views/decorators/cache.py", line 56, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/contrib/admin/sites.py", line 236, in inner
    return view(request, *args, **kwargs)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1670, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1549, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/contrib/admin/options.py", line 1603, in _changeform_view
    self.log_addition(request, new_object, change_message)
  File "/home/ilyagladky/.local/share/virtualenvs/New_TM-Q2NRt8wX/lib/python3.10/site-packages/django/contrib/admin/options.py", line 822, in log_addition
    object_repr=str(obj),
  File "/home/ilyagladky/Projects/New_TM/TaskManagerApp/models.py", line 51, in __str__
    return self.TFullName
AttributeError: 'Person' object has no attribute 'TFullName'
"POST /admin/TaskManagerApp/person/add/ HTTP/1.1" 500 112858
